version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./src/app/Dockerfile
    image: ssimedockerhub/diabetes_prediction:latest
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1